[build]
  command = "cd oracle-app && npm ci --include=dev && npm run build"
  publish = "oracle-app/.next"
  base = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
