[build]
  command = "cd oracle-app && npm ci --include=dev && npm run build"
  publish = "oracle-app/.next"
  base = "."

[build.environment]
  NODE_ENV = "production"

# Next.js Netlify Plugin for proper API route handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions configuration for API routes
[functions]
  external_node_modules = ["@anthropic-ai/sdk", "@supabase/supabase-js", "openai"]
  node_bundler = "esbuild"
  directory = "oracle-app/.netlify/functions"

# No redirects needed - Next.js plugin handles routing
